server:
  port: 2333

spring:
  redis:
    port: 6379
    host: 192.168.2.233

anselyuki:
  jwt:
    header: Authorization
    expire: 21600 #过期时间，以秒为单位
    secret: $I_Am_The_Bone_Of_My_Sword!Steel_Is_My_Body_And_Fire_Is_My_Blood!$

springdoc:
  swagger-ui:
    # 开启Swagger UI界面
    enabled: true
  api-docs:
    # 开启api-docs
    enabled: true
  # 配置需要生成接口文档的扫描包
  packages-to-scan: plus.maa.backend