spring:
  profiles:
    active: template
  jackson:
    property-naming-strategy: SNAKE_CASE
  data:
    mongodb:
      # 打开自动索引生成（否则数据库内唯一索引不生效
      auto-index-creation: true

  #整点花活qwq 是不是瞬间就高大上起来了
  banner:
    location:
      classpath: banner.txt

server:
  # 8848钛金接口.jpg
  port: 8848

logging:
  file:
    name: ./logs/latest.log
  logback:
    rollingpolicy:
      max-history: 14
      clean-history-on-start: true