spring:
  # 不是本地部署的Redis或者修改端口的记得修改Redis配置
  redis:
    port: 6379
    host: localhost

maa-copilot:
  jwt:
    header: Authorization
    # 默认的JwtToken过期时间，以秒为单位
    expire: 21600
    # JwtToken的加密密钥
    secret: $I_Am_The_Bone_Of_My_Sword!Steel_Is_My_Body_And_Fire_Is_My_Blood!$

springdoc:
  swagger-ui:
    # 开启Swagger UI界面
    enabled: true
  api-docs:
    # 开启api-docs
    enabled: true
  # 配置需要生成接口文档的扫描包
  packages-to-scan: plus.maa.backend