spring:
  profiles:
    active: template
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      # 打开自动索引生成（否则数据库内唯一索引不生效
      auto-index-creation: true
  freemarker:
    check-template-location: false
  # 缓存配置，使用caffeine缓存框架，缓存时长为5分钟，最大缓存数量500
  cache:
    cache-names: arkLevel, arkLevels, copilotPage
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=300s
server:
  # 8848钛金接口.jpg
  port: 8848
  tomcat:
    #限制post表单最大为30KB
    max-http-form-post-size: 30KB

logging:
  file:
    name: ./logs/latest.log
  logback:
    rollingpolicy:
      max-history: 14
      clean-history-on-start: true