version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - ../.data:/data/db
    ports:
      - "27017:27017"
    restart: always
